### ISSUE TITLE
Footer not developed yet

### ISSUE THREAD

**Issue by devsdenepal** [NepTechTribe/neptechtribe.github.io#10]
# Required footer
![Group 633077](https://github.com/user-attachments/assets/1fbe554b-cd51-4297-8a73-3bfa8fa0257d)
- [ ] Develop Footer

**Comment by Isabelle36** [comment]
Do you still need the help with ur footer ?? i am new in this all type of github things but still i can help

**Comment by devsdenepal** [comment]
This issue has been assigned to @shree404. She is currently working on it. Let her respond if she needs help.
